Full Focus
VK-BMSTU-QA/homework-selenium-2024-autumn pull request #10
Opened 2024-12-05 13:09 UTC by Olegsandrik

2024-12-05 13:37 UTC, BeeHeather requested changes

2024-12-05 13:37 UTC, BeeHeather commented on hw/code/tests/vk_ads_campany_test.py
> +        time.sleep(3)
Неявные ожидания стоит убрать везде, это антипаттерн

2024-12-05 13:37 UTC, BeeHeather commented on hw/code/tests/vk_ads_campany_test.py
> +    def test_campany_filtr_open(self):
Добавь в тесты проверки состояния после выполнения действий

2024-12-05 13:46 UTC, BeeHeather requested changes
Привет! Поправьте замечания, пожалуйста

2024-12-05 13:46 UTC, BeeHeather commented on hw/code/tests/settings_test.py
> +        time.sleep(1)
Стоит либо это убрать, либо заменить на явное ожидание

2024-12-05 14:21 UTC, BeeHeather approved these changes
Аппрув

2024-12-05 15:28 UTC, alexey-ershkov commented on hw/code/ui/locators/campany_locators.py
> +    IS_SAVED_FILTR = (By.XPATH, '//div//[@class"SavedFilters_wrapper__fsh6J"]')
Такие селекторы могут поменяться, не стоит на них завязываться

2024-12-17 20:13 UTC, BeeHeather requested changes

2024-12-17 20:13 UTC, BeeHeather commented on hw/code/tests/settings_test.py
> +    @pytest.mark.skip('skip')
А почему тесты скипаются?

2024-12-17 20:13 UTC, BeeHeather commented on hw/code/ui/locators/login_locators.py
> +    COUNTIUE_LOGIN = (By.XPATH, "//div[@class='vkuiSimpleCell vkuiSimpleCell--sizeY-none vkuiTappable vkuiTappable--sizeX-none vkuiTappable--hasPointer-none vkuiClickable__host vkuiClickable__realCli
Давайте упростим этот локатор

2024-12-17 20:45 UTC, Olegsandrik commented on hw/code/ui/locators/login_locators.py
> +    COUNTIUE_LOGIN = (By.XPATH, "//div[@class='vkuiSimpleCell vkuiSimpleCell--sizeY-none vkuiTappable vkuiTappable--sizeX-none vkuiTappable--hasPointer-none vkuiClickable__host vkuiClickable__realCli
поменяли на test-data-id, который сделали специально для тестирования)

2024-12-17 20:45 UTC, Olegsandrik commented on hw/code/tests/settings_test.py
> +    @pytest.mark.skip('skip')
убрали

2024-12-17 21:00 UTC, BeeHeather approved these changes
Аппрув

2024-12-17 21:04 UTC, alexey-ershkov commented on hw/code/tests/base_case.py
> +            self.overview_page = login_page.login(credentials)
поправьте переносы на новую строку в конце файлов пж, гитхаб подсвечивает

2024-12-17 21:07 UTC, alexey-ershkov commented on hw/code/tests/vk_ads_campany_test.py
> +            CampanyPageLocators.OPEN_CREATION_NEW_CAMPANY, timeout=10
Тест точно ничего не должен знать про клики и локаторы - подобные штуки нужно уносить в страницу здесь и далее

2024-12-17 21:07 UTC, alexey-ershkov commented on hw/code/tests/vk_ads_campany_test.py
> +            "Тестовое описаниеи ограничениефффффффффффффффффффффффффффффффффффффффффффффффффффффффффффффффффффффффффффффффффффффффффффффффффффффффффффффффффффффффффффффффффффффффффффффффффффффффффффф
Точно в константы/дикты уносить

2024-12-17 21:08 UTC, alexey-ershkov commented on hw/code/tests/vk_ads_campany_test.py
> +        WebDriverWait(self.driver, 20).until(
Веб драйвера в тестах тоже не должно быть - уносите все в страницу

2024-12-17 21:09 UTC, alexey-ershkov commented on hw/code/ui/locators/login_locators.py
> +    COUNTIUE_LOGIN = (By.XPATH, "//div[@data-test-id='organization-item-4410346']")
есть уверенность, что номер в локаторе не изменится после следующего релиза?

2024-12-17 21:11 UTC, alexey-ershkov commented on hw/code/tests/vk_ads_campany_test.py
> +import json
А где тесты на лидформы? на бюджет? кажется только один из двух чеклистов сделан в ДЗ

2024-12-19 09:04 UTC, alexey-ershkov approved these changes

2025-02-02 22:35 UTC, closed without merging